---
title: "Lasso regression analyses (2 and supplemental)"
author: "Jason W. Gullifer & Debra Titone"
date: '2019-07-24'
output:
  html_document:
    fig_height: 7
    fig_width: 8
    toc: yes
  pdf_document:
    toc: yes
  word_document:
    toc: yes
---
# Preliminaries
```{r pre, echo=F, include=F}
source("loadPackages.R")
source("utilityFunctions.R")

registerDoParallel(4)

knitr::opts_chunk$set(cache = TRUE)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(tidy = TRUE)
knitr::opts_chunk$set(fig.path='figures/analysis_2_lasso_prediction/')
knitr::opts_chunk$set(fig.show='hold')

set.seed(420)
```

# Loading data
```{r}
exec_lhq<- as.data.table(fread("subjectdata/axcpt_lhq_data_forpub.csv"))
axcpt <- as.data.table(fread("rawdata/axcpt_trial_data.csv",stringsAsFactors = F, sep=","))
```

# Create folds
```{r}
k=10
k_loo = length(unique(exec_lhq$participant))

exec_lhq$participant <- as.factor(exec_lhq$participant)
exec_lhq <- fold(exec_lhq, k = k, id_col = 'participant') %>% ungroup()
exec_lhq <- fold(exec_lhq, k = k_loo, id_col = 'participant') %>% ungroup()
exec_lhq$participant <- as.numeric(as.character(exec_lhq$participant))

exec_lhq <- exec_lhq %>% 
  rename(.folds10 = .folds_1, .folds.loo = .folds_2)
```

# Entropy PCA and scaling of variables
```{r}
exec_lhq_ppd <- preprocess_steps(exec_lhq)
```

# Join LHQ and AXCPT
```{r results='hide', warning = FALSE}
# Merge behavioral and subject data (restricting to only those in subject data frame)
axcpt_ppd <- left_join(axcpt, exec_lhq_ppd, by="participant",suffix=c(".x",""))
axcpt_ppd <- axcpt_preprocess(axcpt_ppd)

sd.rt <- axcpt_ppd %>% 
  group_by(participant) %>% 
  summarise(meanRT = mean(RT_correct,na.rm=T)) %>% 
  ungroup()

sd.rt <- sd.rt %>% mutate(gmean = mean(meanRT), 
                          gsd = sd(meanRT),
                          lower = gmean - 2.5*gsd,
                          upper = gmean + 2.5*gsd,
                          outlier = ifelse(meanRT >= lower & meanRT <= upper,"fine","outlier"))

sd.acc <- axcpt_ppd %>% 
  group_by(participant) %>% 
  summarise(meanAcc=mean(accuracy_target))

exclude <- sd.rt$participant[sd.rt$outlier=="outlier"]

axcpt_ppd <- axcpt_ppd[!(axcpt_ppd$participant %in% exclude),]

exec_lhq_ppd <- exec_lhq_ppd[!(exec_lhq_ppd$participant %in% exclude),]


exec_lhq_ppd$participant <- as.factor(exec_lhq_ppd$participant)
exec_lhq_ppd <- fold(exec_lhq_ppd, k = k_loo - length(exclude), id_col = 'participant', handle_existing_fold_cols = "remove") %>% ungroup()
exec_lhq_ppd$participant <- as.numeric(as.character(exec_lhq_ppd$participant))


k_loo = k_loo - length(exclude)

exec_lhq_ppd <- exec_lhq_ppd %>% 
  rename(.folds.loo = .folds)

newfolds <- exec_lhq_ppd %>% select(participant, .folds.loo)

axcpt_ppd <- axcpt_ppd %>% select(-`.folds.loo`)
axcpt_ppd <- axcpt_ppd %>% left_join(newfolds)
```

# Jobs data
```{r}
axcpt_ppd$occupation <- factor(axcpt_ppd$occupation)
contrasts(axcpt_ppd$occupation) <- contr.sum(4)
```

# Experiment version
```{r}
axcpt_ppd$ExperimentName <- factor(axcpt_ppd$ExperimentName)
contrasts(axcpt_ppd$ExperimentName) <- contr.sum(3)
```


# Analysis 2: AXCPT GLMNET
```{r}
axcpt_ppd <- axcpt_ppd[axcpt_ppd$Condition !="AX",]
axcpt_ppd.rt <- axcpt_ppd[!is.na(axcpt_ppd$RT_correct),]
```

## 10-fold cross-validation
### RT
```{r}
mm_rt = model.matrix(RT_correct  ~  aoa * (Condition*L2_exposure + Condition*PCA_Work + Condition*PCA_General),data=axcpt_ppd.rt)

axcpt.rt.lasso = cv.glmnet(x=mm_rt,y=axcpt_ppd.rt$RT_correct, type.measure = "mse",
                        parallel = T, 
                        foldid = as.numeric(axcpt_ppd.rt$.folds10))

axcpt.rt.lasso.error <- data.frame(lambda=axcpt.rt.lasso$lambda, cvm=axcpt.rt.lasso$cvm,
                                 cvlo=axcpt.rt.lasso$cvlo, cvup=axcpt.rt.lasso$cvup,
                                 lambda.min=axcpt.rt.lasso$lambda.min, 
                                 lambda.1se = axcpt.rt.lasso$lambda.1se, 
                                 error_metric=axcpt.rt.lasso$name)

p1 <- axcpt.rt.lasso.error %>% 
  ggplot(aes(x=log(lambda), y=cvm, ymin=cvlo, ymax=cvup)) + 
  geom_point(colour="red") + geom_errorbar() +  
  geom_vline(aes(xintercept = log(lambda.1se)), linetype = 4) +
  geom_vline(aes(xintercept = log(lambda.min)), linetype = 3) + 
  theme_minimal(base_size = 12) + ylab(axcpt.rt.lasso$name) + 
  xlab("Regularization parameter: log(\u03BB)") + coord_cartesian(xlim=c(4.5,-3))
ggsave("figures/lasso_axcpt.rt_trial_error_10fold.png", width=17.8, height=11, units="cm")

p2 <- axcpt.rt.lasso$glmnet.fit %>%
  tidy() %>%
  filter(term!="(Intercept)") %>% 
  mutate(term = fct_reorder(term, str_length(term))) %>% 
  ggplot(aes(log(lambda), estimate, color = term)) + 
  geom_line(size=1.15) +
  geom_hline(yintercept = 0, linetype = "solid") + 
  geom_vline(xintercept = log(axcpt.rt.lasso$lambda.1se), linetype = 4) +
  geom_vline(xintercept = log(axcpt.rt.lasso$lambda.min), linetype = 3) + 
  theme_minimal(base_size = 12) + guides(colour=guide_legend("Effect", ncol=1)) +
  ylab("Model estimate") + xlab("Regularization parameter: log(\u03BB)") + coord_cartesian(xlim=c(4.5,-3))
ggsave("figures/lasso_axcpt.rt_trial_10fold.png", width=17.8, height=11, units="cm")

(plot <- ggarrange(p1,p2, nrow = 2, labels=c("A","B"), common.legend = T, legend = "right", align = "v"))
ggsave(plot = plot, file="figures/lasso_axcpt_rt_trial_10fold_2row.png", width=17.8, height=22.5, units="cm")


axcpt.rt_fit <- axcpt.rt.lasso$glmnet.fit %>%
  tidy() %>% 
  filter(lambda == axcpt.rt.lasso$lambda.min)
axcpt.rt_fit

axcpt.rt_fit <- axcpt.rt.lasso$glmnet.fit %>%
  tidy() %>% 
  filter(lambda == axcpt.rt.lasso$lambda.1se)
axcpt.rt_fit

```

### ACC
```{r}
mm_acc = model.matrix(accuracy_target  ~  aoa * (Condition*L2_exposure + Condition*PCA_Work + Condition*PCA_General),data=axcpt_ppd)

axcpt.acc.lasso = cv.glmnet(x=mm_acc,y=axcpt_ppd$accuracy_target,
                        family="binomial", parallel = T,
                        foldid = as.numeric(axcpt_ppd$.folds10))

axcpt.acc.lasso.error <- data.frame(lambda=axcpt.acc.lasso$lambda, cvm=axcpt.acc.lasso$cvm,
                                 cvlo=axcpt.acc.lasso$cvlo, cvup=axcpt.acc.lasso$cvup,
                                 lambda.min=axcpt.acc.lasso$lambda.min, 
                                 lambda.1se = axcpt.acc.lasso$lambda.1se, 
                                 error_metric=axcpt.acc.lasso$name)

p1 <- axcpt.acc.lasso.error %>% 
  ggplot(aes(x=log(lambda), y=cvm, ymin=cvlo, ymax=cvup)) + 
  geom_point(colour="red") + geom_errorbar() +  
  geom_vline(aes(xintercept = log(lambda.1se)), linetype = 4) +
  geom_vline(aes(xintercept = log(lambda.min)), linetype = 3) + 
  theme_minimal(base_size = 12) + ylab(axcpt.acc.lasso$name) + 
  xlab("Regularization parameter: log(\u03BB)") + coord_cartesian(xlim=c(-8.5,-2))
ggsave("figures/lasso_axcpt.acc_trial_error_10fold.png", width=17.8, height=11, units="cm")

p2 <- axcpt.acc.lasso$glmnet.fit %>%
  tidy() %>%
  filter(term!="(Intercept)") %>% 
  mutate(term = fct_reorder(term, str_length(term))) %>% 
  ggplot(aes(log(lambda), estimate, color = term)) + 
  geom_line(size=1.15) +
  geom_hline(yintercept = 0, linetype = "solid") + 
  geom_vline(xintercept = log(axcpt.acc.lasso$lambda.1se), linetype = 4) +
  geom_vline(xintercept = log(axcpt.acc.lasso$lambda.min), linetype = 3) + 
  theme_minimal(base_size = 12) + guides(colour=guide_legend("Effect", ncol=1)) +
  ylab("Model estimate") + xlab("Regularization parameter: log(\u03BB)") +  coord_cartesian(xlim=c(-8.5,-2))
ggsave("figures/lasso_axcpt.acc_trial_10fold.png", width=17.8, height=11, units="cm")

(plot <- ggarrange(p1,p2, nrow = 2, labels=c("A","B"), common.legend = T, legend = "right", align = "v"))
ggsave(plot = plot, file="figures/lasso_axcpt_acc_trial_10fold_2row.png", width=17.8, height=22.5, units="cm")

axcpt.acc_fit <- axcpt.acc.lasso$glmnet.fit %>%
  tidy() %>% 
  filter(lambda == axcpt.acc.lasso$lambda.1se)
axcpt.acc_fit

```

## LOO cross-validation
### RT
```{r}
mm_rt = model.matrix(RT_correct  ~  aoa * (Condition*L2_exposure + Condition*PCA_Work + Condition*PCA_General),data=axcpt_ppd.rt)

#Unstandardized RT
axcpt.rt.lasso = cv.glmnet(x=mm_rt,y=axcpt_ppd.rt$RT_correct, type.measure = "mse", 
                        parallel = T,
                        foldid = as.numeric(axcpt_ppd.rt$.folds.loo), standardize=T)

# Standardized RT
# axcpt.rt.lasso = cv.glmnet(x=mm_rt,y=scale(axcpt_ppd.rt$RT_correct), type.measure = "mse", 
#                         parallel = T,
#                         foldid = as.numeric(axcpt_ppd.rt$.folds.loo), standardize=T)

axcpt.rt.lasso.error <- data.frame(lambda=axcpt.rt.lasso$lambda, cvm=axcpt.rt.lasso$cvm,
                                 cvlo=axcpt.rt.lasso$cvlo, cvup=axcpt.rt.lasso$cvup,
                                 lambda.min=axcpt.rt.lasso$lambda.min, 
                                 lambda.1se = axcpt.rt.lasso$lambda.1se, 
                                 error_metric=axcpt.rt.lasso$name)

p1 <- axcpt.rt.lasso.error %>% 
  ggplot(aes(x=log(lambda), y=sqrt(cvm), ymin=sqrt(cvlo), ymax=sqrt(cvup))) + 
  geom_point(colour="red") + geom_errorbar() +  
  geom_vline(aes(xintercept = log(lambda.1se)), linetype = 4, size=1) +
  geom_vline(aes(xintercept = log(lambda.min)), linetype = 3, size=1) + 
  theme_minimal(base_size = 12) + ylab("RMSE") + 
  xlab("Regularization parameter: log(\u03BB)") + coord_cartesian(xlim=c(4.5,-3))
ggsave("figures/lasso_axcpt.rt_trial_error_loo.png", width=17.8, height=11, units="cm")


terms <- axcpt.rt.lasso$glmnet.fit %>%
  tidy() %>%
  filter(term!="(Intercept)") %>% 
  mutate(term = str_replace(term, "Condition","TrialType")) %>% 
  mutate(term = fct_reorder(term, str_length(term))) %>% 
  select(term) 
terms <- levels(terms$term)
pal <- rep("#A9A9A9", length(terms))

# ConditionAX, CondiitonAY, ConditionBY, PCA_Work, PCA_General, aoa:PCA_Work, aoa:PCA_General
# These colors are hacked together by hand. If you run some other model and the effects change they the coloring won't be accurate. Sorry!

pal <- data.frame(terms, pal, stringsAsFactors = F)
pal$pal[pal$term=="TrialTypeAY"] <- brewer.pal(n = 4, name = "Set1")[1]
pal$pal[pal$term=="TrialTypeBY"] <- brewer.pal(n = 4, name = "Set1")[3]
pal$pal[pal$term=="PCA_Work"] <- brewer.pal(n = 4, name = "Set1")[4]

pal$pal[pal$term=="TrialTypeAY:L2_exposure"] <- brewer.pal(n = 4, name = "Set1")[4]
pal$pal[pal$term=="TrialTypeAY:PCA_General"] <- brewer.pal(n = 4, name = "Set1")[4]
pal$pal[pal$term=="TrialTypeBY:PCA_General"] <- brewer.pal(n = 4, name = "Set1")[4]
pal$pal[pal$term=="aoa:PCA_Work"] <- brewer.pal(n = 4, name = "Set1")[4]
pal$pal[pal$term=="aoa:PCA_General"] <- brewer.pal(n = 4, name = "Set1")[4]

p2 <- axcpt.rt.lasso$glmnet.fit %>%
  tidy() %>%
  filter(term!="(Intercept)") %>% 
  mutate(term = str_replace(term, "Condition","TrialType")) %>% 
  mutate(term = fct_reorder(term, str_length(term))) %>% 
  ggplot(aes(log(lambda), estimate, group = term, colour=term)) + 
  geom_line(size=1.15) +
  geom_hline(yintercept = 0, linetype = "solid") + 
  geom_vline(xintercept = log(axcpt.rt.lasso$lambda.1se), linetype = 4, size=1) +
  geom_vline(xintercept = log(axcpt.rt.lasso$lambda.min), linetype = 3, size=1) + 
  theme_minimal(base_size = 12) + guides(colour=guide_legend("Effect", ncol = 1)) +
  ylab("Model estimate") + xlab("Regularization parameter: log(\u03BB)") +
  coord_cartesian(xlim=c(4.5,-3)) +
  scale_color_manual(values=pal$pal)
ggsave("figures/lasso_axcpt.rt_trial_loo.png", width=17.8, height=11, units="cm")

p3 <- axcpt.rt.lasso$glmnet.fit %>%
  tidy() %>%
  filter(term!="(Intercept)") %>% 
  mutate(term = str_replace(term, "Condition","TrialType")) %>% 
  mutate(term = fct_reorder(term, str_length(term))) %>% 
  ggplot(aes(log(lambda), estimate, group = term, colour=term)) + 
  geom_line(size=1.15) +
  geom_hline(yintercept = 0, linetype = "solid") + 
  geom_vline(xintercept = log(axcpt.rt.lasso$lambda.1se), linetype = 4, size=1) +
  geom_vline(xintercept = log(axcpt.rt.lasso$lambda.min), linetype = 3, size=1) + 
  theme_minimal(base_size = 12) + guides(colour=guide_legend("Effect", ncol = 1)) +
  ylab("Model estimate") + xlab("Regularization parameter: log(\u03BB)") +
  coord_cartesian(xlim=c(4.5,-3), ylim =c(-25,25)) +
  scale_color_manual(values=pal$pal)
ggsave("figures/lasso_axcpt.rt_trial_loo_zoom.png", width=17.8, height=11, units="cm")

(plot <- ggarrange(p1,p2, nrow = 2,labels=c("A","B"), common.legend = T, legend = "right", align = "v"))
ggsave(plot = plot, file="figures/lasso_axcpt_rt_trial_loo_2row.png", width=17.8, height=22.5, units="cm")

print_cval(axcpt.rt.lasso.error, sqrt=T)

min.estimate.rt <- axcpt.rt.lasso$glmnet.fit %>%
  tidy() %>%
  filter(term != "(Intercept)", lambda==axcpt.rt.lasso$lambda.min) %>% 
  mutate(term = str_replace(term, "Condition","TrialType")) %>% 
  mutate(term = fct_reorder(term, c(1,2,3,4,5,6,7,8))) %>% 
  ggplot(aes(term, estimate, fill=term)) + 
  geom_col(width=.9) +
  geom_hline(yintercept = 0, size=.33) +
  theme_minimal(base_size = 12) +  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylab("Model Estimate") + xlab("")  + guides(fill=F) +
  scale_fill_manual(name="Effect", values = c(brewer.pal(n = 4, name = "Set1")[1],brewer.pal(n = 4, name = "Set1")[3],brewer.pal(n = 4, name = "Set1")[4],brewer.pal(n = 4, name = "Set1")[4],brewer.pal(n = 4, name = "Set1")[4],brewer.pal(n = 4, name = "Set1")[4],brewer.pal(n = 4, name = "Set1")[4],brewer.pal(n = 4, name = "Set1")[4]))
ggsave(file="figures/lasso_axcpt_rt_trial_loo_effects.png", width=15, height=12, units="cm")



#pal$pal[pal$term=="ConditionAY"] <- brewer.pal(n = 4, name = "Set1")[1]
#pal$pal[pal$term=="ConditionBY"] <- brewer.pal(n = 4, name = "Set1")[3]
#pal$pal[pal$term=="PCA_Work"] <- brewer.pal(n = 4, name = "Set1")[4]


axcpt.rt_fit <- axcpt.rt.lasso$glmnet.fit %>%
  tidy() %>% 
  filter(lambda == axcpt.rt.lasso$lambda.min)
axcpt.rt_fit

axcpt.rt_fit <- axcpt.rt.lasso$glmnet.fit %>%
  tidy() %>% 
  filter(lambda == axcpt.rt.lasso$lambda.1se)
axcpt.rt_fit

r2 <- axcpt.rt.lasso$glmnet.fit$dev.ratio[which(axcpt.rt.lasso$glmnet.fit$lambda == axcpt.rt.lasso$lambda.min)]

r2 <- axcpt.rt.lasso$glmnet.fit$dev.ratio[which(axcpt.rt.lasso$glmnet.fit$lambda == axcpt.rt.lasso$lambda.1se)]
```


### ACC
```{r}
mm_acc = model.matrix(accuracy_target  ~  aoa * (Condition*L2_exposure + Condition*PCA_Work + Condition*PCA_General),data=axcpt_ppd)

axcpt.acc.lasso = cv.glmnet(x=mm_acc,y=axcpt_ppd$accuracy_target, 
                        family="binomial", parallel = T,
                        foldid = as.numeric(axcpt_ppd$.folds.loo))

axcpt.acc.lasso.error <- data.frame(lambda=axcpt.acc.lasso$lambda, cvm=axcpt.acc.lasso$cvm,
                                 cvlo=axcpt.acc.lasso$cvlo, cvup=axcpt.acc.lasso$cvup,
                                 lambda.min=axcpt.acc.lasso$lambda.min, 
                                 lambda.1se = axcpt.acc.lasso$lambda.1se, 
                                 error_metric=axcpt.acc.lasso$name)

p1 <- axcpt.acc.lasso.error %>% 
  ggplot(aes(x=log(lambda), y=cvm, ymin=cvlo, ymax=cvup)) + 
  geom_point(colour="red") + geom_errorbar() +  
  geom_vline(aes(xintercept = log(lambda.1se)), linetype = 4, size=1) +
  geom_vline(aes(xintercept = log(lambda.min)), linetype = 3, size=1) + 
  theme_minimal(base_size = 12) + ylab(axcpt.acc.lasso$name) + 
  xlab("Regularization parameter: log(\u03BB)") + coord_cartesian(xlim=c(-8.5,-2))
ggsave("figures/lasso_axcpt.acc_trial_error_loo.png", width=17.8, height=11, units="cm")


terms <- axcpt.acc.lasso$glmnet.fit %>%
  tidy() %>%
  filter(term!="(Intercept)") %>% 
  mutate(term = fct_reorder(term, str_length(term))) %>% 
  select(term) 
terms <- levels(terms$term)
pal <- rep("#A9A9A9", length(terms))

pal <- data.frame(terms, pal, stringsAsFactors = F)
pal$pal[pal$term=="ConditionAY"] <- brewer.pal(n = 5, name = "Set1")[1]
pal$pal[pal$term=="ConditionBY"] <- brewer.pal(n = 5, name = "Set1")[3]
pal$pal[pal$term=="L2_exposure"]  <- brewer.pal(n = 5, name = "Set1")[4]
pal$pal[pal$term=="ConditionAY:L2_exposure"]  <- brewer.pal(n = 5, name = "Set1")[4]
pal$pal[pal$term=="ConditionAY:PCA_General"]  <- brewer.pal(n = 5, name = "Set1")[4]
pal$pal[pal$term=="aoa:L2_exposure"]  <- brewer.pal(n = 5, name = "Set1")[4]
pal$pal[pal$term=="aoa:PCA_Work"]  <- brewer.pal(n = 5, name = "Set1")[4]


p2 <- axcpt.acc.lasso$glmnet.fit %>%
  tidy() %>%
  filter(term!="(Intercept)") %>% 
  mutate(term = fct_reorder(term, str_length(term))) %>% 
  ggplot(aes(log(lambda), estimate, color = term)) + 
  geom_line(size=1.15) +
  geom_hline(yintercept = 0, linetype = "solid") + 
  geom_vline(xintercept = log(axcpt.acc.lasso$lambda.1se), linetype = 4, size=1) +
  geom_vline(xintercept = log(axcpt.acc.lasso$lambda.min), linetype = 3, size=1) + 
  theme_minimal(base_size = 12) + guides(colour=guide_legend("Effect", ncol=1)) +
  ylab("Model estimate") + xlab("Regularization parameter: log(\u03BB)") +
  coord_cartesian(xlim=c(-8.5,-2))+
  scale_color_manual(values = pal$pal)

ggsave("figures/lasso_axcpt.acc_trial_loo.png", width=17.8, height=11, units="cm")

(plot <- ggarrange(p1,p2, nrow = 2, labels=c("A","B"), common.legend = T, legend = "right", align = "v"))
ggsave(plot = plot, file="figures/lasso_axcpt_acc_trial_loo_2row.png", width=17.8, height=22.5, units="cm")


print_cval(axcpt.acc.lasso.error)


min.estimate.acc <- axcpt.acc.lasso$glmnet.fit %>%
  tidy() %>%
  filter(term != "(Intercept)", lambda==axcpt.acc.lasso$lambda.min) %>% 
  mutate(term = fct_reorder(term, str_length(term))) %>% 
  ggplot(aes(term, estimate, fill=term)) + 
  geom_col(width=.9) +
  geom_hline(yintercept = 0, size=.33) +
  theme_minimal(base_size = 12) + theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylab("Model Estimate") + xlab("") + guides(fill=F)+
  scale_fill_manual(name="Effect",values = c(brewer.pal(n = 4, name = "Set1")[1], 
                               brewer.pal(n = 4, name = "Set1")[3], 
                               brewer.pal(n = 4, name = "Set1")[4],
                               brewer.pal(n = 4, name = "Set1")[4],
                               brewer.pal(n = 4, name = "Set1")[4],
                               brewer.pal(n = 4, name = "Set1")[4],
                               brewer.pal(n = 4, name = "Set1")[4],
                               brewer.pal(n = 4, name = "Set1")[4]))
ggsave(file="figures/lasso_axcpt_acc_trial_loo_effects.png", width=15, height=12, units="cm")



axcpt.acc_fit <- axcpt.acc.lasso$glmnet.fit %>%
  tidy() %>% 
  filter(lambda == axcpt.acc.lasso$lambda.min)
axcpt.acc_fit

axcpt.acc_fit <- axcpt.acc.lasso$glmnet.fit %>%
  tidy() %>% 
  filter(lambda == axcpt.acc.lasso$lambda.1se)
axcpt.acc_fit

```

## Combined effects plot
```{r}
(plot <- ggarrange(min.estimate.rt,min.estimate.acc, ncol = 2,labels=c("A","B"), common.legend = T, legend = "right", align = "h"))

ggsave(filename = "figures/combine_min_effects_plot.png", plot = plot, height=17.8, width=22.5, units="cm")
```


# Supplementary analysis LHQ GLMNET 
## LOO cross validation
### L2 Accent
```{r}
accent_mm <- model.matrix(meanAccent ~ aoa * L2_exposure + aoa * 
                          PCA_General + aoa * PCA_Work, data=exec_lhq_ppd)

accent.lasso = cv.glmnet(x=accent_mm,
                         y=exec_lhq_ppd$meanAccent, type.measure = "mse",
                         parallel = T, 
                         foldid = as.numeric(exec_lhq_ppd$.folds.loo))

accent.lasso.error <- data.frame(lambda=accent.lasso$lambda, cvm=accent.lasso$cvm,
                                 cvlo=accent.lasso$cvlo, cvup=accent.lasso$cvup,
                                 lambda.min=accent.lasso$lambda.min, 
                                 lambda.1se = accent.lasso$lambda.1se, 
                                 error_metric=accent.lasso$name)

p1 <- accent.lasso.error %>% 
  ggplot(aes(x=log(lambda), y=sqrt(cvm), ymin=sqrt(cvlo), ymax=sqrt(cvup))) + 
  geom_point(colour="red") + geom_errorbar() +  
  geom_vline(aes(xintercept = log(lambda.1se)), linetype = 4) +
  geom_vline(aes(xintercept = log(lambda.min)), linetype = 3) + 
  theme_minimal(base_size = 12) + ylab("RMSE") + xlab("Regularization parameter: log(\u03BB)") + coord_cartesian(xlim=c(0,-6))
ggsave("figures/lasso_accent_error_loo.png", width=17.8, height=11, units="cm")

p2 <- accent.lasso$glmnet.fit %>%
  tidy() %>%
  filter(term!="(Intercept)") %>% 
  mutate(term = fct_reorder(term, str_length(term))) %>% 
  ggplot(aes(log(lambda), estimate, color = term)) + 
  geom_line(size=1.15) +
  geom_hline(yintercept = 0, linetype = "solid") + 
  geom_vline(xintercept = log(accent.lasso$lambda.1se), linetype = 4) +
  geom_vline(xintercept = log(accent.lasso$lambda.min), linetype = 3) + 
  #scale_color_brewer(palette = "Dark2") +
  theme_minimal(base_size = 12) + guides(colour=guide_legend("Effect", ncol=1)) +
  ylab("Model estimate") + xlab("Regularization parameter: log(\u03BB)") + coord_cartesian(xlim=c(0,-6))
ggsave("figures/lasso_accent_loo.png", width=17.8, height=11, units="cm")

(plot <- ggarrange(p1,p2, nrow = 2, labels=c("A","B"), common.legend = T, legend = "right", align = "v"))
ggsave(plot = plot, file="figures/lasso_accent_loo_2row.png", width=17.8, height=22.5, units="cm")


print_cval(accent.lasso.error, sqrt=T)


accent_fit <- accent.lasso$glmnet.fit %>%
  tidy() %>% 
  filter(lambda == accent.lasso$lambda.min)
accent_fit

accent_fit <- accent.lasso$glmnet.fit %>%
  tidy() %>% 
  filter(lambda == accent.lasso$lambda.1se)
accent_fit

```

### L2 Abilities
```{r}
abilities_mm <- model.matrix(meanL2ability ~ aoa * L2_exposure + aoa * 
                          PCA_General + aoa * PCA_Work, data=exec_lhq_ppd)


abilities.lasso = cv.glmnet(x=abilities_mm,y=exec_lhq_ppd$meanL2ability, type.measure = "mse",
                            parallel = T, 
                            foldid = as.numeric(exec_lhq_ppd$.folds.loo))

abilities.lasso.error <- data.frame(lambda=abilities.lasso$lambda, cvm=abilities.lasso$cvm,
                                 cvlo=abilities.lasso$cvlo, cvup=abilities.lasso$cvup,
                                 lambda.min=abilities.lasso$lambda.min, 
                                 lambda.1se = abilities.lasso$lambda.1se, 
                                 error_metric=abilities.lasso$name)

p1 <- abilities.lasso.error %>% 
  ggplot(aes(x=log(lambda), y=cvm, ymin=cvlo, ymax=cvup)) + 
  geom_point(colour="red") + geom_errorbar() +  
  geom_vline(aes(xintercept = log(lambda.1se)), linetype = 4) +
  geom_vline(aes(xintercept = log(lambda.min)), linetype = 3) + 
  theme_minimal(base_size = 12) + ylab(abilities.lasso$name) + 
  xlab("Regularization parameter: log(\u03BB)") + coord_cartesian(xlim=c(0,-6))
ggsave("figures/lasso_abilities_error_loo.png", width=17.8, height=11, units="cm")

p2 <- abilities.lasso$glmnet.fit %>%
  tidy() %>%
  filter(term!="(Intercept)") %>% 
  mutate(term = fct_reorder(term, str_length(term))) %>% 
  ggplot(aes(log(lambda), estimate, color = term)) + 
  geom_line(size=1.15) +
  geom_hline(yintercept = 0, linetype = "solid") + 
  geom_vline(xintercept = log(abilities.lasso$lambda.1se), linetype = 4) +
  geom_vline(xintercept = log(abilities.lasso$lambda.min), linetype = 3) + 
  #scale_color_brewer(palette = "Dark2") +
  theme_minimal(base_size = 12) + guides(colour=guide_legend("Effect", ncol=1)) +
  ylab("Model estimate") + xlab("Regularization parameter: log(\u03BB)") + coord_cartesian(xlim=c(0,-6))
ggsave("figures/lasso_abilities_loo.png", width=17.8, height=11, units="cm")

(plot <- ggarrange(p1,p2, nrow = 2, labels=c("A","B"), common.legend = T, legend = "right", align = "v"))
ggsave(plot = plot, file="figures/lasso_ablities_loo_2row.png", width=17.8, height=22.5, units="cm")


print_cval(abilities.lasso.error, sqrt = T)

abilities_fit <- abilities.lasso$glmnet.fit %>%
  tidy() %>% 
  filter(lambda == abilities.lasso$lambda.min)
abilities_fit


abilities_fit <- abilities.lasso$glmnet.fit %>%
  tidy() %>% 
  filter(lambda == abilities.lasso$lambda.1se)
abilities_fit

```

