---
title: "Data plots and tables"
author: "Jason W. Gullifer & Debra Titone"
date: '2019-07-24'
output:
  html_document:
    fig_height: 7
    fig_width: 8
    toc: yes
  pdf_document:
    toc: yes
  word_document:
    toc: yes
---

# Preliminaries
```{r pre, echo=F, include=F}
source("loadPackages.R")
source("utilityFunctions.R")

registerDoParallel(4)

knitr::opts_chunk$set(cache = TRUE)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(tidy = TRUE)
knitr::opts_chunk$set(fig.path='figures/plots_tables_subject_data/')
knitr::opts_chunk$set(fig.show='hold')

set.seed(420)
```

# Loading data
```{r}
exec_lhq<- as.data.table(fread("subjectdata/axcpt_lhq_data_forpub.csv"))
axcpt <- as.data.table(fread("rawdata/axcpt_trial_data.csv",stringsAsFactors = F, sep=","))
```

# Table of participant demographics
```{r include=FALSE}
data.agg <- exec_lhq %>% select(participant,age,
                                aoa,
                                yearsBilingual,
                                L1_current_exposure,
                                L2_current_exposure,
                                L3_current_exposure,
                                ReadEntropy,
                                SpeakEntropy,
                                HomeEntropy,
                                WorkEntropy,
                                SocialEntropy,
                                meanAccent,
                                meanL2ability)

stargazer(data.agg, type="html", out="tables/summary_stats.html")
```

# Entropy PCA and scaling of variables
```{r}
exec_lhq_ppd <- preprocess_steps(exec_lhq)
```

# Join LHQ and AXCPT
```{r results='hide', warning = FALSE}
axcpt_ppd <- left_join(axcpt, exec_lhq_ppd, by="participant",suffix=c(".x",""))
axcpt_ppd <- axcpt_preprocess(axcpt_ppd)
```

# Data plots

## Group level
```{r}
sd.rt  <- sem(axcpt_ppd, RT_correct, participant, Condition)
sd.acc <- sem(axcpt_ppd, accuracy_target, participant, Condition)

p1 <- ggplot(sd.rt, aes(x=Condition,y=mean_RT_correct,ymin=lower,ymax=upper, fill=Condition)) + 
	geom_col() + geom_errorbar(width=.2) +
	ylab("Mean RT (in ms)") + xlab("Condition") +
	theme_minimal(base_size = 12) + scale_fill_brewer(palette = "Set1")


p2 <- ggplot(sd.acc, aes(x=Condition,y=mean_accuracy_target,ymin=lower,ymax=upper, fill=Condition)) +
	geom_col() + geom_errorbar(width=.2) +
	ylab("Mean accuracy") + xlab("Condition") +
	theme_minimal(base_size = 12) + scale_fill_brewer(palette = "Set1")

(plot <- ggarrange(p1, p2, nrow=2, labels=c("A","B"), common.legend = T, legend = "right", align = "v"))
ggsave(plot=plot, file="figures/mean_acc_rt.png", width=8.7, height=11, units="cm")
```

## RT: individual differences
```{r}
rt.sd <- axcpt_ppd %>% 
  group_by(participant, L2_current_exposure, aoa, PCA_General, PCA_Work, Condition) %>% 
  summarise(meanRT=mean(RT_correct, na.rm=T), 
            sdRT = sd(RT_correct, na.rm=T),
            N=n(),
            semRT = sdRT/sqrt(N))

p1 <- ggplot(rt.sd, aes(x=aoa, y = meanRT, colour=Condition))+ geom_smooth(method="lm") +
  geom_point(alpha=.2) +
  ylab("Reaction time (in ms)") + xlab("L2 AoA") +
  theme_minimal(base_size = 12) + scale_colour_brewer(palette = "Set1")

p2 <- ggplot(rt.sd, aes(x=L2_current_exposure, y = meanRT, colour=Condition)) +
    geom_point(alpha=.2) +
  geom_smooth(method="lm") + ylab("Reaction time (in ms)") + xlab("L2 current exposure") +
  theme_minimal(base_size = 12) + scale_colour_brewer(palette = "Set1")

p3 <- ggplot(rt.sd, aes(x=PCA_General, y = meanRT, colour=Condition)) +
  geom_smooth(method="lm") +  geom_point(alpha=.2) +
	ylab("Reaction time (in ms)") + xlab("PC: General entropy") +
	theme_minimal(base_size = 12) + scale_colour_brewer(palette = "Set1")

p4 <- ggplot(rt.sd, aes(x=PCA_Work, y = meanRT, colour=Condition)) +
  geom_smooth(method="lm")+   geom_point(alpha=.2) +
	ylab("Reaction time (in ms)") + xlab("PC: Work entropy") +
	theme_minimal(base_size = 12) + scale_colour_brewer(palette = "Set1")


(plot <- ggarrange(p1,p2,p3,p4, nrow=2, ncol=2, labels = c("A","B","C","D"), common.legend = T, legend="right", align = "hv"))
ggsave(plot=plot, file="figures/rt_by_id.png", width=17.8, height=17.5, units="cm")
```

## ACC: individual differences
```{r}
acc.sd <- axcpt_ppd %>% 
  group_by(participant, L2_current_exposure, aoa, PCA_General, PCA_Work, Condition) %>% 
  summarise(meanACC=mean(accuracy_target, na.rm=T), 
            sdACC = sd(accuracy_target, na.rm=T),
            N=n(),
            semACC = sdACC/sqrt(N))

p1 <- ggplot(acc.sd, aes(x=aoa, y = meanACC, colour=Condition))+ geom_smooth(method="lm") +
  geom_point(alpha=.2) +
  ylab("Mean accuracy") + xlab("L2 AoA") +
  theme_minimal(base_size = 12) + scale_colour_brewer(palette = "Set1")

p2 <- ggplot(acc.sd, aes(x=L2_current_exposure, y = meanACC, colour=Condition)) +
    geom_point(alpha=.2) +
  geom_smooth(method="lm") + ylab("Mean accuracy") + xlab("L2 current exposure") +
  theme_minimal(base_size = 12) + scale_colour_brewer(palette = "Set1")

p3 <- ggplot(acc.sd, aes(x=PCA_General, y = meanACC, colour=Condition)) +
  geom_smooth(method="lm") +  geom_point(alpha=.2) +
	ylab("Mean accuracy") + xlab("PC: General entropy") +
	theme_minimal(base_size = 12) + scale_colour_brewer(palette = "Set1")

p4 <- ggplot(acc.sd, aes(x=PCA_Work, y = meanACC, colour=Condition)) +
  geom_smooth(method="lm")+   geom_point(alpha=.2) +
	ylab("Mean accuracy") + xlab("PC: Work entropy") +
	theme_minimal(base_size = 12) + scale_colour_brewer(palette = "Set1")


(plot <- ggarrange(p1,p2,p3,p4, nrow=2, ncol=2, labels = c("A","B","C","D"), common.legend = T, legend="right", align = "hv"))
ggsave(plot=plot, file="figures/acc_by_id.png", width=17.8, height=17.5, units="cm")

```